### ISSUE TITLE
Can't attack phantoms using the usual red button even when spotted. 

### ISSUE THREAD

**Issue by Omicronrg9** [TrashboxBobylev/Summoning-Pixel-Dungeon#12]
![Screenshot_20210524-062836](https://user-images.githubusercontent.com/13071402/119296509-5c34af80-bc59-11eb-90b1-113827fe54f2.png)

**Comment by Omicronrg9** [comment]
Regarding phantoms too. They have no level cap.
![Screenshot_20210524-064127](https://user-images.githubusercontent.com/13071402/119297401-25f82f80-bc5b-11eb-9c88-9f3625d36cc5.png)

**Comment by TrashboxBobylev** [comment]
> https://github.com/TrashboxBobylev/Summoning-Pixel-Dungeon/issues/12#issue-899233041

Intended.

**Comment by TrashboxBobylev** [comment]
> https://github.com/TrashboxBobylev/Summoning-Pixel-Dungeon/issues/12#issuecomment-846728067
Already reported.
