### ISSUE TITLE
Idea: make abilities upgradeable.

### ISSUE THREAD

**Issue by heliah2004** [TrashboxBobylev/Summoning-Pixel-Dungeon#26]
Like wands, summoning staffs and the bow, abilities also have a tier symbol. However, i noticed that it could not be upgraded.
Abilities like heroic leap, elemental blast and wild magic could gain certain bonusses tier four talents would normally give, while others could be buffed in various ways, like more area of effect, more buff duration, etc.

**Comment by TrashboxBobylev** [comment]
This is already in process, but I got distracted by minor issues.
