### ISSUE TITLE
Rogue talents review.

### ISSUE THREAD

**Issue by heliah2004** [TrashboxBobylev/Summoning-Pixel-Dungeon#27]
Overall the talent system for the rogue is quite entertaining. However, there are some flaws.
-hyperspace. Although a usefull talent, the way it basically sabotages easy quickslot use is too annoying, so i advise to give it either a choice menu like the hourglass or a last ability button like the soul of yendor. (The lattter could be usefull if you plan to create more cloak-related talents in the future, which I definitely would appreciate, unless overdone of course.)
Edit: alternatively, hyperspace could completely overhaul how the cloak works by first letting you warp and then giving you the amount of cloaking you would get from that amount of charges (minus a bit of course, maybe 3 turns per charge?) This would make it a completely new mechanic people can toy around, although it seems a bit too powerfull for tier one, so maybe it should become tier 2 or ever 3 then. Anyways, i really like this idea, way more then the other two actually.
-balancing. Some talents are just more powerfull then others. Directive, for ecample, seems more like tier one to me, while life on the axiom, thaumium infuse and lethal momentum could be really powerfull if used right (but not so powerfull that it completely outranges the others.)
-weird talents. Scrap brain and plaguebringer, as well as welcome to earth, are just a bit... weird. There is nothing specific against them but I just feel the need to point out that I really don't like them anyway, and I wonder whether it's just me or more people think this too. If i am the only one then maybe don't do anything about them, as they are not inherently flawed.

**Comment by TrashboxBobylev** [comment]
Directive is very strong thing if used right.

Weird talents are here for diversity as they have potential for buildmaking.
