### ISSUE TITLE
Unenterable rooms, yet still you can teleport there.

### ISSUE THREAD

**Issue by Lovecutehuy1943** [TrashboxBobylev/Summoning-Pixel-Dungeon#39]
Imagine using a scroll of teleportation just to get teleported into an unenterable room which is what has happened to me.
![Annotation 2021-09-13 142034](https://user-images.githubusercontent.com/87656308/133040695-7a87cdb5-6d94-4542-b24d-b358dc1acfb0.png)
(I'm glad that I have an unstable spellbook during that game)

**Comment by TrashboxBobylev** [comment]
Please update to latest snapshot before reporting things.

This looks like 1.2.1, which was released 2 months ago.

**Comment by Lovecutehuy1943** [comment]
Oh ok

**Comment by Lovecutehuy1943** [comment]
Well then should I delete this post?

**Comment by Lovecutehuy1943** [comment]
I think I should close this then

**Comment by Lovecutehuy1943** [comment]
Sorry for making this report without updating the game
