### ISSUE TITLE
Невероятно быстрое истощение с испытанием "нырок в хаос"

### ISSUE THREAD

**Issue by Xazmadan** [TrashboxBobylev/Summoning-Pixel-Dungeon#40]
каждый удар существа(любого) или получение любого физического урона за исключением урона от падения снимает 5% голода, из-за чего продвинуться дальше 1 уровня во всех типах уровня за исключением уменьшенного и обычного становится невероятно сложно, и практически невозможно. Также рандомизатор часто превращает оружие т-1 в игрушечный нож Призывателя, что вызывает вылет и перезапуск уровня и в редких случаях удаление сохранения

**Comment by TrashboxBobylev** [comment]
какая версия? и можно название испытания на английском?

**Comment by Xazmadan** [comment]
Entropy dive испытание, версия текущая

**Comment by TrashboxBobylev** [comment]
Воспроизвел.
