### ISSUE TITLE
Rat King bug. "Cornucopia" (It's my name for this bug)

### ISSUE THREAD

**Issue by gfbbkon** [TrashboxBobylev/Summoning-Pixel-Dungeon#62]
I decided to officially document this bug in the "Issues". Its essence is simple: you need to make sure that the Rat King cannot throw an object at you. This can be done using the level itself or by using a special wand to stop it moving.
Link to Reddit, where i found this bug: https://www.reddit.com/r/PixelDungeon/comments/158d69g/experienced_pd_balance_breaking_mechanic/

**Comment by TrashboxBobylev** [comment]
While I appreciate this report, this is wrong repo.
