### ISSUE TITLE
axiom nexus inside out making prison mobs spawn in sewer, undergound gold mine mobs spawn in prison, etc. +exploration death bugs

### ISSUE THREAD

**Issue by littleBob138** [TrashboxBobylev/Summoning-Pixel-Dungeon#65]
when i play axiom nexus inside out, the game continues with the whole 7 layers per area but treats spawn mechanics as if it were 5 layers per area. bandits start spawning in the sewer at layer 6, rattlesnakes start spawning in the prison at layer 11, dwarf mobs spawn in the mine at level 16, etc. also, when i am on exploration and are starving, i take damage every time i go up or down a layer. if i happen to be low on health, i will die, and cant respawn. 

also, even though this isnt an issue, i would like to suggest a way to be able to have multiple conducts and gamemodes. i understand if that will take a very long time, though, so don't rush yourself. i have no doubt that (for example) making axiom nexus inside out and extra enlargement and subterranean diversity all work together will be a nightmare, so take as much time as you need

also dear my irl brother (not u trashboxboblydev, i mean my irl brother) if u say this is me "messing with your account", im bringing a couple glitches that should be fixed AND a suggestion to the spotlight to make this summoning pixel dungeon better.

**Comment by TrashboxBobylev** [comment]
Multiple conducts are possible if you disable Balanced Conducts option in game's settings.

Multiple game modes will never be a thing, the best thing is that some of them could be turned into conducts.

> when i play axiom nexus inside out, the game continues with the whole 7 layers per area but treats spawn mechanics as if it were 5 layers per area. bandits start spawning in the sewer at layer 6, rattlesnakes start spawning in the prison at layer 11, dwarf mobs spawn in the mine at level 16, etc.

Known issue, would think about it once game modes will come into Reincarnated... The game spawns enemies via Bestiary class, which is kind of hardcoded to disperse mobs over specific depths, while Axiom Nexus Inside Out is percentage increase to chapter length.

> also, when i am on exploration and are starving, i take damage every time i go up or down a layer. if i happen to be low on health, i will die, and cant respawn.

That's... the consequence of both hunger rework and transitions depleting hunger when player has no control, could be interesting to solve... not sure how, though.

---
Just so you know, feature additions or changes will no longer come into original Summoning PD, as Summoning: ReIncarnated is planned to replace it.
