### ISSUE TITLE
The .jar file is missing .class files

### ISSUE THREAD

**Issue by RID-developer** [TrashboxBobylev/Summoning-Pixel-Dungeon#67]
I compiled the game on arch linux, after fixing java versions the ,jar file, both the one from releases and the compiled one were missing files from updates and news, now i cannot tell much since i forgot 3 seconds after fixing the file (by manually added the classes in the archive) but it was from updates and news

**Comment by TrashboxBobylev** [comment]
Since legacy Summoning doesn't use news nor updates scene, it doesn't matter.
